# Generated by Django 5.2.16 on 2026-07-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improve_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementtask',
            name='benefit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='improvementtask',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
