# Generated by Django 5.2.16 on 2026-07-25 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_sip', models.IntegerField(default=0)),
                ('target_value', models.IntegerField(default=0)),
                ('horizon_years', models.IntegerField(default=5)),
                ('expected_cagr', models.CharField(default='10-12%', max_length=20)),
                ('confidence_score', models.IntegerField(default=0)),
                ('risk_bucket', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_profiles',
            },
        ),
        migrations.CreateModel(
            name='InvestmentGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('color_theme', models.CharField(default='green', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance', to='investment.investmentprofile')),
            ],
            options={
                'db_table': 'investment_guidance',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('allocation_pct', models.IntegerField()),
                ('expected_cagr_range', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=50)),
                ('is_highly_recommended', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investment.investmentprofile')),
            ],
            options={
                'db_table': 'investment_assets',
                'ordering': ['-allocation_pct'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_theme', models.CharField(default='green', max_length=50)),
                ('emoji', models.CharField(default='🛡️', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='investment.investmentprofile')),
            ],
            options={
                'db_table': 'investment_benefits',
            },
        ),
    ]
