# Generated by Django 5.2.16 on 2026-07-26 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSignalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electricity_bill_frequency', models.CharField(choices=[('always_on_time', 'Always On Time'), ('occasionally_late', 'Occasionally Late'), ('frequently_late', 'Frequently Late'), ('no_bills', 'No Bills')], default='always_on_time', max_length=30)),
                ('water_bill_frequency', models.CharField(choices=[('always_on_time', 'Always On Time'), ('occasionally_late', 'Occasionally Late'), ('frequently_late', 'Frequently Late'), ('no_bills', 'No Bills')], default='always_on_time', max_length=30)),
                ('gas_bill_frequency', models.CharField(choices=[('always_on_time', 'Always On Time'), ('occasionally_late', 'Occasionally Late'), ('frequently_late', 'Frequently Late'), ('no_bills', 'No Bills')], default='no_bills', max_length=30)),
                ('mobile_recharge_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('irregular', 'Irregular'), ('prepaid', 'Prepaid Auto-Recharge')], default='monthly', max_length=30)),
                ('broadband_payment', models.CharField(choices=[('always_on_time', 'Always On Time'), ('occasionally_late', 'Occasionally Late'), ('no_broadband', 'No Broadband')], default='always_on_time', max_length=30)),
                ('upi_transaction_frequency', models.CharField(choices=[('multiple_daily', 'Multiple Times a Day'), ('daily', 'Daily'), ('weekly', 'Few Times a Week'), ('rarely', 'Rarely'), ('never', 'Never')], default='daily', max_length=30)),
                ('card_transaction_frequency', models.CharField(choices=[('multiple_daily', 'Multiple Times a Day'), ('daily', 'Daily'), ('weekly', 'Few Times a Week'), ('rarely', 'Rarely'), ('never', 'Never')], default='weekly', max_length=30)),
                ('shopping_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely')], default='monthly', max_length=30)),
                ('utility_payment_regularity', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=30)),
                ('online_spending_behaviour', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low'), ('minimal', 'Minimal')], default='moderate', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Signal Profile',
                'db_table': 'digital_signal_profiles',
            },
        ),
    ]
