# Generated by Django 5.2.16 on 2026-07-26 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(db_index=True, default='General', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(db_index=True, default='Unread', max_length=20)),
                ('notification_type', models.CharField(db_column='type', default='Information', max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='notifications.notification')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bills', models.BooleanField(default=True)),
                ('investments', models.BooleanField(default=True)),
                ('credit_score', models.BooleanField(default=True)),
                ('education', models.BooleanField(default=True)),
                ('security', models.BooleanField(default=True)),
                ('ai_insights', models.BooleanField(default=True)),
                ('reports', models.BooleanField(default=True)),
                ('goals', models.BooleanField(default=True)),
                ('achievements', models.BooleanField(default=True)),
                ('simulator', models.BooleanField(default=True)),
                ('risk_profile', models.BooleanField(default=True)),
                ('dashboard', models.BooleanField(default=True)),
                ('profile', models.BooleanField(default=True)),
                ('general', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
