# Generated by Django 5.2.16 on 2026-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='numeric_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
