# Generated by Django 5.2.16 on 2026-07-26 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('risk_change', 'Risk Profile Change'), ('goal_progress', 'Goal Progress'), ('goal_completed', 'Goal Completed'), ('credit_change', 'Credit Score Change'), ('investment_update', 'Investment Update'), ('learning_milestone', 'Learning Milestone'), ('transaction_pattern', 'Transaction Pattern'), ('behavior_change', 'Behaviour Change'), ('budget_update', 'Budget Update'), ('conversation_summary', 'AI Conversation Summary'), ('notification_event', 'Notification Event'), ('digital_signal_update', 'Digital Signal Update')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_memory_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'memory_type'], name='ai_memory_e_user_id_c9a285_idx'), models.Index(fields=['user', 'created_at'], name='ai_memory_e_user_id_1948e7_idx')],
            },
        ),
    ]
