# Generated by Django 5.2.16 on 2026-07-25 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_score', models.IntegerField(blank=True, null=True)),
                ('current_score', models.IntegerField()),
                ('previous_bucket', models.CharField(blank=True, default='', max_length=50)),
                ('current_bucket', models.CharField(max_length=50)),
                ('assessment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_history',
                'ordering': ['-assessment_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('savings_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expense_ratio_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_surplus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emergency_coverage_months', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_bucket', models.CharField(blank=True, default='', max_length=50)),
                ('confidence_score', models.IntegerField(default=0)),
                ('investment_readiness', models.CharField(blank=True, default='', max_length=50)),
                ('ai_risk_explanation', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profiles',
            },
        ),
        migrations.CreateModel(
            name='RiskFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('impact', models.IntegerField()),
                ('reason', models.TextField()),
                ('is_positive', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='risk_profile.riskprofile')),
            ],
            options={
                'db_table': 'risk_features',
                'ordering': ['-is_positive', '-impact'],
            },
        ),
        migrations.CreateModel(
            name='RiskRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('benefit', models.TextField()),
                ('risk_reduction_estimate', models.IntegerField(default=0)),
                ('priority', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='risk_profile.riskprofile')),
            ],
            options={
                'db_table': 'risk_recommendations',
                'ordering': ['created_at'],
            },
        ),
    ]
