# Generated by Django 5.2.16 on 2026-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskrecommendation',
            options={'ordering': ['-risk_reduction_estimate']},
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_readiness_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_readiness_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='portfolio_allocation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskrecommendation',
            name='estimated_completion_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='riskrecommendation',
            name='estimated_credit_improvement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
