# improve_score/constants.py

TASK_PRIORITY_CRITICAL = 'Critical'
TASK_PRIORITY_HIGH = 'High'
TASK_PRIORITY_MEDIUM = 'Medium'
TASK_PRIORITY_LOW = 'Low'

TASK_DIFFICULTY_EASY = 'Easy'
TASK_DIFFICULTY_MEDIUM = 'Medium'
TASK_DIFFICULTY_HARD = 'Hard'

STATUS_PENDING = 'Pending'
STATUS_IN_PROGRESS = 'In Progress'
STATUS_COMPLETED = 'Completed'

WEEK_STATUS_UPCOMING = 'Upcoming'
WEEK_STATUS_IN_PROGRESS = 'In Progress'
WEEK_STATUS_COMPLETE = 'Complete'
