# Generated by Django 5.2.16 on 2026-07-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('German', 'German')], max_length=30)),
                ('monthly_income', models.CharField(blank=True, max_length=50)),
                ('monthly_expenses', models.CharField(blank=True, max_length=50)),
                ('savings', models.CharField(blank=True, max_length=50)),
                ('existing_loans', models.CharField(blank=True, choices=[('None', 'None'), ('Personal Loan', 'Personal Loan'), ('Education Loan', 'Education Loan'), ('Home Loan', 'Home Loan')], max_length=50)),
                ('upi_usage', models.CharField(blank=True, choices=[('Daily (15+ txns/wk)', 'Daily (15+ txns/wk)'), ('Moderate (5-15 txns/wk)', 'Moderate (5-15 txns/wk)'), ('Rare (1-5 txns/wk)', 'Rare (1-5 txns/wk)')], max_length=50)),
                ('bill_payment_habit', models.CharField(blank=True, choices=[('Always On-Time', 'Always On-Time'), ('Occasionally Delayed', 'Occasionally Delayed'), ('Auto-Debit Enabled', 'Auto-Debit Enabled')], max_length=50)),
                ('investment_experience', models.CharField(blank=True, choices=[('Beginner (< 1 yr)', 'Beginner (< 1 yr)'), ('Intermediate (1-3 yrs)', 'Intermediate (1-3 yrs)'), ('Advanced (3+ yrs)', 'Advanced (3+ yrs)')], max_length=50)),
                ('emergency_fund', models.CharField(blank=True, choices=[('Yes (6 Months Saved)', 'Yes (6 Months Saved)'), ('Yes (3 Months Saved)', 'Yes (3 Months Saved)'), ('Building Currently', 'Building Currently'), ('Not Yet', 'Not Yet')], max_length=50)),
                ('monthly_investment_budget', models.CharField(blank=True, max_length=50)),
                ('financial_goal', models.CharField(blank=True, choices=[('Wealth Accumulation', 'Wealth Accumulation & Growth'), ('Buying a House', 'Buying a House'), ('Retirement Fund', 'Early Retirement Fund'), ('Child Education', 'Education Fund')], max_length=50)),
                ('risk_preference', models.CharField(blank=True, choices=[('Conservative (Low Risk)', 'Conservative (Low Risk)'), ('Moderate (Balanced)', 'Moderate (Balanced Portfolio)'), ('Aggressive (High Growth)', 'Aggressive (High Growth)')], max_length=50)),
                ('investment_duration', models.CharField(blank=True, choices=[('Short-Term (1-3 yrs)', 'Short-Term (1-3 yrs)'), ('Medium-Term (3-5 yrs)', 'Medium-Term (3-5 yrs)'), ('Long-Term (5+ Years)', 'Long-Term (5+ Years)')], max_length=50)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
