# Generated by Django 5.2.16 on 2026-07-26 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('accent_color', models.CharField(default='purple', max_length=20)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('density', models.CharField(default='comfortable', max_length=20)),
                ('language', models.CharField(default='en-US', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('two_factor_ready', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('weekly_reports_email', models.BooleanField(default=True)),
                ('monthly_reports_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
