# Generated by Django 5.2.16 on 2026-07-26 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('merchant', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance Income'), ('investment_income', 'Investment Income'), ('refund', 'Refund'), ('other_income', 'Other Income'), ('groceries', 'Groceries'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('health', 'Health & Medical'), ('education', 'Education'), ('investment', 'Investment'), ('rent', 'Rent'), ('emi', 'EMI / Loan'), ('insurance', 'Insurance'), ('travel', 'Travel'), ('personal_care', 'Personal Care'), ('subscriptions', 'Subscriptions'), ('charity', 'Charity / Donations'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=50)),
                ('original_category', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='upi', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('csv_import', 'CSV Import'), ('upi_sync', 'UPI Sync'), ('card_sync', 'Card Sync'), ('bank_sync', 'Bank Sync'), ('demo', 'Synthetic Demo Data')], default='manual', max_length=30)),
                ('is_income', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_059bf9_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cfabf3_idx'), models.Index(fields=['user', 'is_income'], name='transaction_user_id_d0f1f0_idx')],
            },
        ),
    ]
